name: organizations/321880981428/customConstraints/custom.requireDiskEnvironmentLabel
resourceTypes:
  - compute.googleapis.com/Disk
methodTypes:
  - CREATE
condition: |
  !resource.labels.exists(l, l == "environment")
actionType: DENY
displayName: Require environment label on disks
description: Deny disk creation if the environment label is missing.
