name: Governance Validation

on:
  pull_request:
    branches:
      - main

  push:
    branches:
      - governance-pipeline-poc

jobs:

  validate:

    runs-on: ubuntu-latest

    steps:

      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Setup TFLint
        uses: terraform-linters/setup-tflint@v4

      - name: Terraform Format Check
        run: terraform fmt -check -recursive

      - name: Terraform Init
        run: terraform init
        working-directory: terraform/environments/dev

      - name: Terraform Validate
        run: terraform validate
        working-directory: terraform/environments/dev

      - name: Run TFLint
        run: tflint --recursive || true

      - name: Install Conftest
        run: |
          wget https://github.com/open-policy-agent/conftest/releases/download/v0.59.0/conftest_0.59.0_Linux_x86_64.tar.gz
          tar xzf conftest_0.59.0_Linux_x86_64.tar.gz
          sudo mv conftest /usr/local/bin/

      - name: Verify Conftest
        run: conftest --version

      - name: Terraform Plan
        working-directory: terraform/environments/dev
        env:
          TF_VAR___ADMIN_EMAIL__: ${{ secrets.ADMIN_EMAIL }}
        run: |
          terraform plan -out=tfplan

      - name: Export Terraform Plan JSON
        working-directory: terraform/environments/dev
        run: |
          terraform show -json tfplan > tfplan.json

      - name: Run Governance Policies
        working-directory: terraform/environments/dev
        run: |
          conftest test tfplan.json \
            --policy ../../../policy
