name: Terraform_Validation

on:
push:
branches:
- governance-pipeline-poc

pull_request:
branches:
- main

jobs:
validate:
runs-on: ubuntu-latest


defaults:
  run:
    shell: bash

steps:
  - name: Checkout Repository
    uses: actions/checkout@v4

  - name: Setup Terraform
    uses: hashicorp/setup-terraform@v3

  - name: Terraform Format Check
    run: terraform fmt -check -recursive

  - name: Terraform Init
    working-directory: terraform/environments/dev
    run: terraform init -input=false

  - name: Terraform Validate
    working-directory: terraform/environments/dev
    run: terraform validate

  - name: Setup TFLint
    uses: terraform-linters/setup-tflint@v4

  - name: Run TFLint
    run: |
      tflint --init
      tflint --recursive
