name: Terraform Validation

on:
pull_request:
branches:
- main

push:
branches:
- governance-pipeline-poc

jobs:

validate:

```
runs-on: ubuntu-latest

steps:

  - name: Checkout Code
    uses: actions/checkout@v4

  - name: Setup Terraform
    uses: hashicorp/setup-terraform@v3

  - name: Setup TFLint
    uses: terraform-linters/setup-tflint@v4

  - name: Terraform Format Check
    run: terraform fmt -check -recursive

  - name: Terraform Init
    working-directory: terraform/environments/dev
    run: terraform init

  - name: Terraform Validate
    working-directory: terraform/environments/dev
    run: terraform validate

  - name: Run TFLint
    run: tflint --recursive

  - name: Install Conftest
    run: |
      wget https://github.com/open-policy-agent/conftest/releases/latest/download/conftest_Linux_x86_64.tar.gz
      tar xzf conftest_Linux_x86_64.tar.gz
      sudo mv conftest /usr/local/bin/

  - name: Generate Terraform Plan
    working-directory: terraform/environments/dev
    run: |
      terraform plan -out=tfplan.binary
      terraform show -json tfplan.binary > tfplan.json

  - name: Run Governance Policies
    working-directory: terraform/environments/dev
    run: |
      conftest test tfplan.json \
        --policy ../../../policy
```
